package com.andreikslpv.domain.entities

data class CardModel(
    val availableCards: MutableList<AvailableCardModel> = mutableListOf(),
    val artist: String = "",
    val cmc: Double =0.0,
    val colorIdentity: List<String> = listOf(),
    val colors: List<String> = listOf(),
    val flavor: String = "",
    val foreignNames: List<ForeignNameModel> = listOf(),
    val id: String = "",
    val imageUrl: String = "",
    val layout: String = "",
    val manaCost: String = "",
    val multiverseid: String = "",
    val name: String = "",
    val number: String = "",
    val originalText: String = "",
    val originalType: String = "",
    val power: String = "",
    val printings: List<String> = listOf(),
    val rarity: String = "",
    val set: String = "",
    val setName: String = "",
    val subtypes: List<String> = listOf(),
    val text: String = "",
    val toughness: String = "",
    val type: String = "",
    val types: List<String> = listOf(),
    val watermark: String = "",
) : java.io.Serializable
